name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set image version
        id: docker_image_version
        run: |
          if ["{{ github.ref_name }} " == "main" ]; then
            DOCKER_IMAGE_VERSION="1.0.${{ github.event.pull_request.number }}"
          else
            DOCKER_IMAGE_VERSION="0.${{ github.event.pull_request.number }}.${{ github.run_number }}"
          fi
          echo "Docker Image Tag: $DOCKER_IMAGE_TAG"
          
      - name: login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build dockerfile
        run: |
          docker build -t ryanleetecheer/actions-test:? .
          docker push ryanleetecheer/actions-test:?